
spring:
  session:
    store-type: NONE
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.fondue/db/h2;AUTO_SERVER=TRUE
    username: sa
    password: sa

#server:
#  contextPath: 
#  session:
#    timeout: 10800

logging:
  level:
    app: DEBUG
