
appName: app1
rootPkg: app

preparationMode: NONE # BACKUP/OVERWRITE/NONE
backupSettings:
  directory: ./.bak
  subDirectoryPattern: "%2$tY%2$tm%2$td_%2$tH%2$tM%2$tS_%3$02d" # 1: (empty), 2: Timestamp, 3: SeqNum
  fileNamePattern: "{0}.bak" # 1: FileName, 2: Timestamp, 3: SeqNum

# [NamePattern]
#   Formatter-style: %1$s_%2$tY%2$tm%2$td_%3$02d
#   MessageFormat-style {0}_{1,Date,yyyyMMddHHmmss}_{2,Number,00}

funcs:
 - name: book
   resourceName: books
   groupBy: # not implemented
   validations:
     - field: title
       type: Size
       appendingAttributes: min = 1
     - field: bookNumber
       type: Pattern
       appendingAttributes: regexp = "^\\d*$"
     - field: bookNumber
       type: Size
       appendingAttributes: max = 16
   dao:
      tableId: app1.books
      clauseBeforeLoop: "disabled = '0'"
      clauseInLoop: "(title like '%'||#{keywords[\" + i + \"]}||'%' or author like '%'||#{keywords[\" + i + \"]}||'%')"
      clauseAfterLoop: "1 = 1"
      orderBy: "updated desc"
 - name: remark
   resourceName: remarks
