package app.model;

import java.util.Date;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP1.BOOKS.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP1.BOOKS.CREATED
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP1.BOOKS.UPDATED
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP1.BOOKS.DISABLED
     *
     * @mbg.generated
     */
    private Short disabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP1.BOOKS.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP1.BOOKS.AUTHOR
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP1.BOOKS.BOOK_NUMBER
     *
     * @mbg.generated
     */
    private String bookNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP1.BOOKS.SUMMARY
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP1.BOOKS.NOTE
     *
     * @mbg.generated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP1.BOOKS.ID
     *
     * @return the value of APP1.BOOKS.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP1.BOOKS.ID
     *
     * @param id the value for APP1.BOOKS.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP1.BOOKS.CREATED
     *
     * @return the value of APP1.BOOKS.CREATED
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP1.BOOKS.CREATED
     *
     * @param created the value for APP1.BOOKS.CREATED
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP1.BOOKS.UPDATED
     *
     * @return the value of APP1.BOOKS.UPDATED
     *
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP1.BOOKS.UPDATED
     *
     * @param updated the value for APP1.BOOKS.UPDATED
     *
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP1.BOOKS.DISABLED
     *
     * @return the value of APP1.BOOKS.DISABLED
     *
     * @mbg.generated
     */
    public Short getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP1.BOOKS.DISABLED
     *
     * @param disabled the value for APP1.BOOKS.DISABLED
     *
     * @mbg.generated
     */
    public void setDisabled(Short disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP1.BOOKS.TITLE
     *
     * @return the value of APP1.BOOKS.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP1.BOOKS.TITLE
     *
     * @param title the value for APP1.BOOKS.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP1.BOOKS.AUTHOR
     *
     * @return the value of APP1.BOOKS.AUTHOR
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP1.BOOKS.AUTHOR
     *
     * @param author the value for APP1.BOOKS.AUTHOR
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP1.BOOKS.BOOK_NUMBER
     *
     * @return the value of APP1.BOOKS.BOOK_NUMBER
     *
     * @mbg.generated
     */
    public String getBookNumber() {
        return bookNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP1.BOOKS.BOOK_NUMBER
     *
     * @param bookNumber the value for APP1.BOOKS.BOOK_NUMBER
     *
     * @mbg.generated
     */
    public void setBookNumber(String bookNumber) {
        this.bookNumber = bookNumber == null ? null : bookNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP1.BOOKS.SUMMARY
     *
     * @return the value of APP1.BOOKS.SUMMARY
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP1.BOOKS.SUMMARY
     *
     * @param summary the value for APP1.BOOKS.SUMMARY
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP1.BOOKS.NOTE
     *
     * @return the value of APP1.BOOKS.NOTE
     *
     * @mbg.generated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP1.BOOKS.NOTE
     *
     * @param note the value for APP1.BOOKS.NOTE
     *
     * @mbg.generated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.BOOKS
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", disabled=").append(disabled);
        sb.append(", title=").append(title);
        sb.append(", author=").append(author);
        sb.append(", bookNumber=").append(bookNumber);
        sb.append(", summary=").append(summary);
        sb.append(", note=").append(note);
        sb.append("]");
        return sb.toString();
    }
}