package app.dao;

import app.model.Remark;
import app.model.RemarkExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface RemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.REMARKS
     *
     * @mbg.generated
     */
    long countByExample(RemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.REMARKS
     *
     * @mbg.generated
     */
    int deleteByExample(RemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.REMARKS
     *
     * @mbg.generated
     */
    @Delete({
        "delete from APP1.REMARKS",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.REMARKS
     *
     * @mbg.generated
     */
    @Insert({
        "insert into APP1.REMARKS (CREATED, UPDATED, ",
        "DISABLED, USER_ID, ",
        "USER_NAME, REMARK)",
        "values (#{created,jdbcType=TIMESTAMP}, #{updated,jdbcType=TIMESTAMP}, ",
        "#{disabled,jdbcType=SMALLINT}, #{userId,jdbcType=VARCHAR}, ",
        "#{userName,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.REMARKS
     *
     * @mbg.generated
     */
    int insertSelective(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.REMARKS
     *
     * @mbg.generated
     */
    List<Remark> selectByExampleWithRowbounds(RemarkExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.REMARKS
     *
     * @mbg.generated
     */
    List<Remark> selectByExample(RemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.REMARKS
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, CREATED, UPDATED, DISABLED, USER_ID, USER_NAME, REMARK",
        "from APP1.REMARKS",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("app.dao.RemarkMapper.BaseResultMap")
    Remark selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.REMARKS
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Remark record, @Param("example") RemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.REMARKS
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Remark record, @Param("example") RemarkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.REMARKS
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP1.REMARKS
     *
     * @mbg.generated
     */
    @Update({
        "update APP1.REMARKS",
        "set CREATED = #{created,jdbcType=TIMESTAMP},",
          "UPDATED = #{updated,jdbcType=TIMESTAMP},",
          "DISABLED = #{disabled,jdbcType=SMALLINT},",
          "USER_ID = #{userId,jdbcType=VARCHAR},",
          "USER_NAME = #{userName,jdbcType=VARCHAR},",
          "REMARK = #{remark,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(Remark record);
}